### ISSUE TITLE
Database missing 

### ISSUE THREAD

**Issue by nirajdhiman123** [khopaderahul01/vehicletracking#2]
HI can u help me with the DB .

**Comment by zoro111** [comment]
yes sure. create a SqlServer script file and add this file to the repository,

**Comment by zoro111** [comment]
did you finally create the script file of your database?

**Comment by khopaderahul01** [comment]
I have uploaded the database scripts.Please Check.

**Comment by nirajdhiman123** [comment]
HI thanx for DB.
can u plz help me with GPSTrackingBLL.dll class library code.

**Comment by nirajdhiman123** [comment]
can u also help me with the some data for all the table in DB..plz its urgent.....

**Comment by nirajdhiman123** [comment]
email id: niraj_dhiman@rediffmail.com .....plz its very urgent
